# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Project/Capstone/Architecture/Architecture.srcs/sources_1/ip/dist_mem_video/dist_mem_video.xci
# IP: The module: 'dist_mem_video' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Project/Capstone/Architecture/Architecture.gen/sources_1/ip/dist_mem_video_1/dist_mem_video_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_video'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/Project/Capstone/Architecture/Architecture.srcs/sources_1/ip/dist_mem_video/dist_mem_video.xci
# IP: The module: 'dist_mem_video' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Project/Capstone/Architecture/Architecture.gen/sources_1/ip/dist_mem_video_1/dist_mem_video_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_video'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
