# clock
set_property PACKAGE_PIN Y9 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
create_clock -period 10.000 -name sys_clk_pin -add [get_ports CLK]

# reset
set_property PACKAGE_PIN T18 [get_ports RST]
set_property IOSTANDARD LVCMOS33 [get_ports RST]

# vga
set_property PACKAGE_PIN AB19 [get_ports {RGB[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[0]}]
set_property PACKAGE_PIN AB20 [get_ports {RGB[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[1]}]
set_property PACKAGE_PIN Y20 [get_ports {RGB[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[2]}]
set_property PACKAGE_PIN Y21 [get_ports {RGB[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[3]}]
set_property PACKAGE_PIN AA21 [get_ports {RGB[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[4]}]
set_property PACKAGE_PIN AB21 [get_ports {RGB[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[5]}]
set_property PACKAGE_PIN AA22 [get_ports {RGB[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[6]}]
set_property PACKAGE_PIN AB22 [get_ports {RGB[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[7]}]
set_property PACKAGE_PIN V18 [get_ports {RGB[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[8]}]
set_property PACKAGE_PIN V19 [get_ports {RGB[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[9]}]
set_property PACKAGE_PIN U20 [get_ports {RGB[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[10]}]
set_property PACKAGE_PIN V20 [get_ports {RGB[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[11]}]
set_property PACKAGE_PIN AA19 [get_ports HSYNC]
set_property IOSTANDARD LVCMOS33 [get_ports HSYNC]
set_property PACKAGE_PIN Y19 [get_ports VSYNC]
set_property IOSTANDARD LVCMOS33 [get_ports VSYNC]

# ps/2
set_property PACKAGE_PIN Y11 [get_ports PS2CLOCK0]
set_property IOSTANDARD LVCMOS33 [get_ports PS2CLOCK0]
set_property PACKAGE_PIN AA11 [get_ports PS2DATA0]
set_property IOSTANDARD LVCMOS33 [get_ports PS2DATA0]
