# clock
set_property PACKAGE_PIN Y9 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
create_clock -period 10.000 -name sys_clk_pin -add [get_ports CLK]

# reset
set_property PACKAGE_PIN T18 [get_ports RST]
set_property IOSTANDARD LVCMOS33 [get_ports RST]

# vga
set_property PACKAGE_PIN AB19 [get_ports {RGB[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[0]}]
set_property PACKAGE_PIN AB20 [get_ports {RGB[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[1]}]
set_property PACKAGE_PIN Y20 [get_ports {RGB[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[2]}]
set_property PACKAGE_PIN Y21 [get_ports {RGB[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[3]}]
set_property PACKAGE_PIN AA21 [get_ports {RGB[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[4]}]
set_property PACKAGE_PIN AB21 [get_ports {RGB[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[5]}]
set_property PACKAGE_PIN AA22 [get_ports {RGB[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[6]}]
set_property PACKAGE_PIN AB22 [get_ports {RGB[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[7]}]
set_property PACKAGE_PIN V18 [get_ports {RGB[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[8]}]
set_property PACKAGE_PIN V19 [get_ports {RGB[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[9]}]
set_property PACKAGE_PIN U20 [get_ports {RGB[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[10]}]
set_property PACKAGE_PIN V20 [get_ports {RGB[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGB[11]}]
set_property PACKAGE_PIN AA19 [get_ports HSYNC]
set_property IOSTANDARD LVCMOS33 [get_ports HSYNC]
set_property PACKAGE_PIN Y19 [get_ports VSYNC]
set_property IOSTANDARD LVCMOS33 [get_ports VSYNC]

# ps/2
set_property PACKAGE_PIN Y11 [get_ports PS2CLOCK0]
set_property IOSTANDARD LVCMOS33 [get_ports PS2CLOCK0]
set_property PULLTYPE PULLUP [get_ports PS2CLOCK0]
set_property PACKAGE_PIN AA11 [get_ports PS2DATA0]
set_property IOSTANDARD LVCMOS33 [get_ports PS2DATA0]
set_property PULLTYPE PULLUP [get_ports PS2DATA0]


set_property MARK_DEBUG true [get_nets design_1_i/Motherboard_0/inst/ps2_controller_keyboard/INT_reg]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[31]}]
set_property MARK_DEBUG true [get_nets design_1_i/Motherboard_0/inst/ps2_controller_keyboard/pulse]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/MDR[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/PC[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/control_unit/next_state[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/control_unit/next_state[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/control_unit/next_state[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/control_unit/next_state[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/control_unit/next_state[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/amo_v1/control_unit/next_state[5]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/clk_wiz_0/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 6 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/Motherboard_0/inst/amo_v1/control_unit/next_state[0]} {design_1_i/Motherboard_0/inst/amo_v1/control_unit/next_state[1]} {design_1_i/Motherboard_0/inst/amo_v1/control_unit/next_state[2]} {design_1_i/Motherboard_0/inst/amo_v1/control_unit/next_state[3]} {design_1_i/Motherboard_0/inst/amo_v1/control_unit/next_state[4]} {design_1_i/Motherboard_0/inst/amo_v1/control_unit/next_state[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[0]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[1]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[2]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[3]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[4]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[5]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[6]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[7]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[8]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[9]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[10]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[11]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[12]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[13]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[14]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[15]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[16]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[17]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[18]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[19]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[20]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[21]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[22]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[23]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[24]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[25]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[26]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[27]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[28]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[29]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[30]} {design_1_i/Motherboard_0/inst/ps2_controller_keyboard/data[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/Motherboard_0/inst/amo_v1/PC[0]} {design_1_i/Motherboard_0/inst/amo_v1/PC[1]} {design_1_i/Motherboard_0/inst/amo_v1/PC[2]} {design_1_i/Motherboard_0/inst/amo_v1/PC[3]} {design_1_i/Motherboard_0/inst/amo_v1/PC[4]} {design_1_i/Motherboard_0/inst/amo_v1/PC[5]} {design_1_i/Motherboard_0/inst/amo_v1/PC[6]} {design_1_i/Motherboard_0/inst/amo_v1/PC[7]} {design_1_i/Motherboard_0/inst/amo_v1/PC[8]} {design_1_i/Motherboard_0/inst/amo_v1/PC[9]} {design_1_i/Motherboard_0/inst/amo_v1/PC[10]} {design_1_i/Motherboard_0/inst/amo_v1/PC[11]} {design_1_i/Motherboard_0/inst/amo_v1/PC[12]} {design_1_i/Motherboard_0/inst/amo_v1/PC[13]} {design_1_i/Motherboard_0/inst/amo_v1/PC[14]} {design_1_i/Motherboard_0/inst/amo_v1/PC[15]} {design_1_i/Motherboard_0/inst/amo_v1/PC[16]} {design_1_i/Motherboard_0/inst/amo_v1/PC[17]} {design_1_i/Motherboard_0/inst/amo_v1/PC[18]} {design_1_i/Motherboard_0/inst/amo_v1/PC[19]} {design_1_i/Motherboard_0/inst/amo_v1/PC[20]} {design_1_i/Motherboard_0/inst/amo_v1/PC[21]} {design_1_i/Motherboard_0/inst/amo_v1/PC[22]} {design_1_i/Motherboard_0/inst/amo_v1/PC[23]} {design_1_i/Motherboard_0/inst/amo_v1/PC[24]} {design_1_i/Motherboard_0/inst/amo_v1/PC[25]} {design_1_i/Motherboard_0/inst/amo_v1/PC[26]} {design_1_i/Motherboard_0/inst/amo_v1/PC[27]} {design_1_i/Motherboard_0/inst/amo_v1/PC[28]} {design_1_i/Motherboard_0/inst/amo_v1/PC[29]} {design_1_i/Motherboard_0/inst/amo_v1/PC[30]} {design_1_i/Motherboard_0/inst/amo_v1/PC[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/Motherboard_0/inst/amo_v1/MDR[0]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[1]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[2]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[3]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[4]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[5]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[6]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[7]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[8]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[9]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[10]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[11]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[12]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[13]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[14]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[15]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[16]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[17]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[18]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[19]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[20]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[21]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[22]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[23]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[24]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[25]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[26]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[27]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[28]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[29]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[30]} {design_1_i/Motherboard_0/inst/amo_v1/MDR[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/Motherboard_0/inst/ps2_controller_keyboard/INT_reg]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/Motherboard_0/inst/ps2_controller_keyboard/pulse]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out1]
