# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Project/Capstone/Architecture/Architecture.srcs/sources_1/bd/design_1/ip/design_1_Motherboard_0_0/design_1_Motherboard_0_0.xci
# IP: The module: 'design_1_Motherboard_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: E:/Project/Capstone/Architecture/Architecture.srcs/sources_1/ip/blk_mem_ram/blk_mem_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_ram || ORIG_REF_NAME==blk_mem_ram} -quiet] -quiet

# IP: E:/Project/Capstone/Architecture/Architecture.srcs/sources_1/ip/dist_mem_video/dist_mem_video.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dist_mem_video || ORIG_REF_NAME==dist_mem_video} -quiet] -quiet

# IP: E:/Project/Capstone/Architecture/Architecture.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dist_mem_gen_0 || ORIG_REF_NAME==dist_mem_gen_0} -quiet] -quiet

# XDC: e:/Project/Capstone/Architecture/Architecture.gen/sources_1/bd/design_1/ip/design_1_Motherboard_0_0/design_1_Motherboard_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_Motherboard_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/Project/Capstone/Architecture/Architecture.srcs/sources_1/bd/design_1/ip/design_1_Motherboard_0_0/design_1_Motherboard_0_0.xci
# IP: The module: 'design_1_Motherboard_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: E:/Project/Capstone/Architecture/Architecture.srcs/sources_1/ip/blk_mem_ram/blk_mem_ram.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_ram || ORIG_REF_NAME==blk_mem_ram} -quiet] -quiet

# IP: E:/Project/Capstone/Architecture/Architecture.srcs/sources_1/ip/dist_mem_video/dist_mem_video.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dist_mem_video || ORIG_REF_NAME==dist_mem_video} -quiet] -quiet

# IP: E:/Project/Capstone/Architecture/Architecture.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dist_mem_gen_0 || ORIG_REF_NAME==dist_mem_gen_0} -quiet] -quiet

# XDC: e:/Project/Capstone/Architecture/Architecture.gen/sources_1/bd/design_1/ip/design_1_Motherboard_0_0/design_1_Motherboard_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_Motherboard_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
