set_property SRC_FILE_INFO {cfile:E:/Project/Capstone/Architecture/Architecture.srcs/constrs_1/new/pin_constraints.xdc rfile:../../../Architecture.srcs/constrs_1/new/pin_constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y9 [get_ports CLK]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T18 [get_ports RST]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB19 [get_ports {RGB[0]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB20 [get_ports {RGB[1]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y20 [get_ports {RGB[2]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y21 [get_ports {RGB[3]}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA21 [get_ports {RGB[4]}]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB21 [get_ports {RGB[5]}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA22 [get_ports {RGB[6]}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB22 [get_ports {RGB[7]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V18 [get_ports {RGB[8]}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V19 [get_ports {RGB[9]}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U20 [get_ports {RGB[10]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V20 [get_ports {RGB[11]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA19 [get_ports HSYNC]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y19 [get_ports VSYNC]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y11 [get_ports PS2CLOCK0]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA11 [get_ports PS2DATA0]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[19]}]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[0]}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[9]}]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[12]}]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[31]}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[20]}]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[21]}]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[24]}]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[26]}]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[29]}]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[10]}]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[2]}]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[30]}]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[7]}]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[11]}]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[13]}]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[14]}]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[16]}]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[18]}]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[28]}]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[1]}]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[5]}]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[15]}]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[17]}]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[23]}]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[25]}]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[3]}]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[4]}]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[6]}]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[8]}]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[22]}]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/Motherboard_0/inst/timer1/seconds_reg[27]}]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/clk_wiz_0/inst/clk_out1]]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/Motherboard_0/inst/timer1/seconds_reg[0]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[1]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[2]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[3]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[4]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[5]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[6]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[7]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[8]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[9]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[10]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[11]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[12]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[13]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[14]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[15]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[16]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[17]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[18]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[19]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[20]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[21]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[22]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[23]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[24]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[25]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[26]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[27]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[28]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[29]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[30]} {design_1_i/Motherboard_0/inst/timer1/seconds_reg[31]}]]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out1]
