# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin_constraints.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Motherboard_0_0/design_1_Motherboard_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_Motherboard_0_0 || ORIG_REF_NAME==design_1_Motherboard_0_0} -quiet] -quiet

# IP: ip/blk_mem_ram/blk_mem_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_ram || ORIG_REF_NAME==blk_mem_ram} -quiet] -quiet

# IP: ip/dist_mem_video/dist_mem_video.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dist_mem_video || ORIG_REF_NAME==dist_mem_video} -quiet] -quiet

# IP: ip/dist_mem_gen_0/dist_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dist_mem_gen_0 || ORIG_REF_NAME==dist_mem_gen_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# XDC: e:/Project/Capstone/Architecture/Architecture.gen/sources_1/bd/design_1/design_1_ooc.xdc
